{
 "title": "MikroTikMonitor",
 "description": "Dashboard to provide basic monitoring of a MikroTik device",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "HOSTNAME",
    "label": "MikroTik Hostname",
    "query": "select hostname, value from cpu_load;"
   },
   {
    "name": "Interface_Name",
    "query": "select interface, value from tx_bps where hostname=~ /^$HOSTNAME/"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory (Total/used)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "Total Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" }
     ]
    },
    {
     "alias": "Used Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Util (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "Tx bps ($Interface_Name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx_bps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$Interface_Name$/" }
     ]
    },
    {
     "alias": "Rx bps ($Interface_Name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rx_bps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$Interface_Name$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Rx FCS Error ($Interface_Name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rx_fcs_error",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$Interface_Name$/" }
     ]
    },
    {
     "alias": "Tx Drops ($Interface_Name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx_drop",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$Interface_Name$/" }
     ]
    }
   ]
  }
 ]
}