apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    user: user
    url: http://localhost:8086
    jsonData:
      dbName: dbName
      httpMode: GET
    secureJsonData:
      password: password
